trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build1
    steps: 
    - bash: echo Build First Job
  - job: Build2
    steps: 
    - bash: echo Build Second Job
    - bash: echo $(ßPipelineLevelVarible)


- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo $(environment)DeployJob

- stage: QADeploy
  variables:
    environment: Dev
  dependsOn: DevDeploy
  jobs:
  - job: QADeployJob
    steps: 
    - bash: echo QADeploy Job

- stage: ProdDeploy
  dependsOn: 
  - QADeploy
  - DevDeploy
  - Build
  jobs:
  - job: ProdDeployJOb
    steps: 
    - bash: echo ProdDeploy Job
