trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build1
    steps: 
    - bash: echo Build First Job 
  - job: Build2
    steps: 
    - bash: echo Build Second Job
    - bash: echo $(PipelineLevelVarible)
    - bash: echo Build Number $(Build.BuildNumber)
    - bash: echo Build ID $(Build.BuildID)
    - bash: echo Source Branch Name $(Build.SourceBranchName)
    - bash: echo Source Directory $(Build.SourceDirectory)
    - bash: echo Default Working Directory $(System.DefaultWorkingDirectory)
    - bash: ls -al $(System.DefaultWorkingDirectory)
    - bash: echo Artifact Working Directory $(Build.ArtifactStagingDirectory)
    - bash: echo Artifact Working Directory $(Build.ArtifactWorkingDirectory)



# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo $(environment)DeployJob

# - stage: QADeploy
#   variables:
#     environment: QA
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps: 
#     - bash: echo $(environment)Deploy Job

# - stage: ProdDeploy
#   dependsOn: 
#   - QADeploy
#   - DevDeploy
#   - Build
#   variables:
#     environment: Prod
#   jobs:
#   - job: ProdDeployJOb
#     steps: 
#     - bash: echo $(environment)Deploy Job
