trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Build First Job
  - job: SecondJob
    steps: 
    - bash: echo Build Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps: 
    - bash: echo DevDeploy Job

- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: QADeployJob
    steps: 
    - bash: echo QADeploy Job

- stage: ProdDeploy
  dependsOn: 
  - QADeploy
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJOb
    steps: 
    - bash: echo ProdDeploy Job
